package com.wrox.beginspring.pix.jms.beans;

import java.io.Serializable;

public class PixPicturePrintRequest implements Serializable {

    private static final long serialVersionUID = 2444140678537508885L;

    // PIX service provides unique client ids for every system it integrates
    // with
    // For PIX system its wroxpix
    private String client;

    // Request id generated by client for tracking.
    private String requestId;

    private String userName;

    private String firstName;

    private String lastName;

    private String email;

    private String pictureName;

    // private byte[] picture;

    // Address information where to ship.

    public String getClient() {
        return client;
    }

    public void setClient(String client) {
        this.client = client;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /*
     * public byte[] getPicture() { return picture; }
     * 
     * public void setPicture(byte[] picture) { this.picture = picture; }
     */

    public String getPictureName() {
        return pictureName;
    }

    public void setPictureName(String pictureName) {
        this.pictureName = pictureName;
    }

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

}
